server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          # In local mode, route to localhost.
          # When running in docker, we override these hostnames.
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/users/**

            - id: pet-service
              uri: http://localhost:8083
              predicates:
                - Path=/pets/**

            - id: vet-service
              uri: http://localhost:8084
              predicates:
                - Path=/vets/**

            - id: record-service
              uri: http://localhost:8085
              predicates:
                - Path=/records/**

            - id: appointment-service
              uri: http://localhost:8086
              predicates:
                - Path=/appointments/**
